spring:
  shardingsphere:
    enabled: true
    datasource:
      # 数据源名字不可以带下划线
      names: master,slave0,slave1
      # 主库
      master:
        jdbc-url: jdbc:mysql://localhost:3306/db?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      # 从库 1
      slave0:
        jdbc-url: jdbc:mysql://192.168.238.150:33006/db?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      # 从库 2
      slave1:
        jdbc-url: jdbc:mysql://192.168.238.151:33006/db?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave0,slave1
    props:
      sql.show: true
mybatis:
  type-aliases-package: com.webbdong.shardingsphere.readwritesplit.entity
