spring:
  shardingsphere:
    enabled: true
    datasource:
      names: ds_master,ds_slave0,ds_slave1
      # 主库
      ds_master:
        jdbc-url: jdbc:mysql://localhost:3306/db?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      # 从库 1
      ds_slave0:
        jdbc-url: jdbc:mysql://192.168.238.150:33006/db?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      # 从库 2
      ds_slave1:
        jdbc-url: jdbc:mysql://192.168.238.151:33006/db?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: ds_master
      slave-data-source-names: ds_slave0,ds_slave1
    props:
      sql.show: true
mybatis:
  type-aliases-package: com.webbdong.shardingsphere.readwritesplit.entity
