spring:
  datasource:
    url: jdbc:mysql://localhost:3307/master_slave_db?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  type-aliases-package: com.webbdong.shardingsphereproxy.readwritesplit.entity
