DROP TABLE IF EXISTS `t_product`;
CREATE TABLE `t_product` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '商品自增ID',
    `brand_id` BIGINT(20) DEFAULT NULL COMMENT '品牌ID',
    `brand_name` VARCHAR(30) DEFAULT NULL COMMENT '品牌名称',
    `category_id` BIGINT(20) DEFAULT NULL COMMENT '商品分类ID',
    `category_name` VARCHAR(255) DEFAULT NULL COMMENT '商品分类名称',
    `name` VARCHAR(64) NOT NULL COMMENT '商品名称',
    `pic` VARCHAR(255) DEFAULT NULL COMMENT '商品图片',
    `product_no` VARCHAR(64) NOT NULL COMMENT '货号',
    `publish_status` TINYINT(1) DEFAULT NULL COMMENT '上架状态：0->下架；1->上架',
    `new_status` TINYINT(1) DEFAULT NULL COMMENT '新品状态:0->不是新品；1->新品',
    `verify_status` TINYINT(1) DEFAULT NULL COMMENT '审核状态：0->未审核；1->审核通过',
    `sort` int(11) DEFAULT NULL COMMENT '排序',
    `sale` int(11) DEFAULT NULL COMMENT '销量',
    `price` decimal(10,2) DEFAULT NULL COMMENT '原价格',
    `promotion_price` decimal(10,2) DEFAULT NULL COMMENT '促销价格',
    `stock` int(11) DEFAULT NULL COMMENT '库存',
    `low_stock` int(11) DEFAULT NULL COMMENT '库存预警值',
    `unit` varchar(16) DEFAULT NULL COMMENT '单位',
    `weight` decimal(10,2) DEFAULT NULL COMMENT '商品重量，默认为克',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `promotion_start_time` datetime DEFAULT NULL COMMENT '促销开始时间',
    `promotion_end_time` datetime DEFAULT NULL COMMENT '促销结束时间',
    `promotion_per_limit` int(11) DEFAULT NULL COMMENT '活动限购数量',
    `created_time`          TIMESTAMP COMMENT '创建时间',
    `updated_time`          TIMESTAMP COMMENT '修改时间',
    `delete_status` TINYINT(1) DEFAULT NULL COMMENT '删除状态：0->未删除；1->已删除',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品表';