spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/db?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        # 以 _ 分割的数据源名，首部为组名，相同组名称的数据源会放在一个组下
        slave_0:
          url: jdbc:mysql://192.168.238.150:33006/db?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        slave_1:
          url: jdbc:mysql://192.168.238.151:33006/db?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
mybatis-plus:
  type-aliases-package: com.webbdong.readwritesplit.entity
  configuration:
    # 设置驼峰命名规则
    map-underscore-to-camel-case: true
