# hardingsphere-4.1.0-sharding-scaling 源配置
# 将一个2个订单分库，每个库16张订单分表，迁移到4个订单分库，每个库64张订单分表中
# 源库和目标库都用 proxy
order_ds_0: !!org.apache.shardingsphere.orchestration.core.configuration.YamlDataSourceConfiguration
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  properties:
    jdbcUrl: jdbc:mysql://localhost:33010/order?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maxPoolSize: 100
    minPoolSize: 10
    maintenanceIntervalMilliseconds: 30000
    readOnly: false
tables:
  t_order:
    actualDataNodes: order_ds_0.t_order
    keyGenerator:
      column: id
      type: SNOWFLAKE